import XCTest
@testable import Zeus

/// Floors on the BUILT app bundle, not on Swift.
///
/// WHY THIS FILE EXISTS. Every other test in this suite asserts about types
/// and functions, and all of them stayed green on a tree that produced an app
/// with NO ICON AT ALL: no asset catalog anywhere in the repo, no tracked
/// image, no `Assets.car` in the product, and no `CFBundleIconName` in the
/// built `Info.plist`. The build was green with zero warnings. `xcodegen`
/// emitted `ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon` by default, pointing
/// at a set that did not exist, and the toolchain said nothing — a missing
/// icon is not a compile error, not a link error, and not a runtime crash.
///
/// It is caught by exactly one gate: App Store validation, which runs AFTER
/// upload. A defect whose only reporter is a submission is a defect that costs
/// a release cycle to find, so these legs move the reporter into the suite.
///
/// APERTURE. These assertions read the product of THIS build, via
/// `Bundle(for:)` on the test class and `TEST_HOST` on the app. They are
/// therefore about packaging, and blind to everything about how the icon
/// LOOKS — an all-black 1024 square passes every assertion here. What they
/// discriminate is present-vs-absent, which is the axis that was silent.
final class BundleResourceTests: XCTestCase {

    /// The app bundle under test, resolved from the unit-test host.
    ///
    /// NOT `Bundle.main` — under a `bundle.unit-test` target `Bundle.main` is
    /// the TEST RUNNER, whose `Info.plist` is generated by
    /// `GENERATE_INFOPLIST_FILE = YES` and would answer these questions about
    /// the wrong product. `Bundle(for:)` locates the test bundle, whose parent
    /// directory is the host app's `.app`. Getting this wrong is the classic
    /// way to write a bundle test that measures an adjacent artifact.
    private func hostAppBundle() throws -> Bundle {
        let testBundle = Bundle(for: type(of: self))
        // …/Zeus.app/PlugIns/ZeusTests.xctest -> …/Zeus.app
        let appURL = testBundle.bundleURL
            .deletingLastPathComponent()   // PlugIns
            .deletingLastPathComponent()   // Zeus.app
        guard let app = Bundle(url: appURL) else {
            throw XCTSkip("host app bundle not resolvable at \(appURL.path)")
        }
        return app
    }

    /// CONTROL FOR THIS FILE'S INSTRUMENT.
    ///
    /// Every other leg here is an ASSERTION OF PRESENCE, and the failure mode
    /// of a presence assertion is that the whole lookup is pointed at the
    /// wrong place — in which case every leg fails together and reads as "the
    /// icon is missing" when it means "the bundle is missing". This leg pins a
    /// key that has been in the tracked `project.yml` since before the catalog
    /// existed. If it fails, the resolution above is wrong and NO verdict in
    /// this file is about the icon.
    func testTheBundleWeResolvedIsActuallyTheApp() throws {
        let app = try hostAppBundle()
        XCTAssertEqual(
            app.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String,
            "Zeus",
            "resolved bundle at \(app.bundleURL.path) is not the Zeus app — "
                + "every other leg in this file is measuring the wrong artifact"
        )
    }

    /// THE LEG THE SILENT ZERO NEEDED.
    ///
    /// `CFBundleIconName` is written into the built plist by the asset catalog
    /// compiler, and ONLY when it actually compiled an icon set of the name in
    /// `ASSETCATALOG_COMPILER_APPICON_NAME`. Its absence is what App Store
    /// validation rejects on. Because the key is produced by the build rather
    /// than declared in `project.yml`, this cannot be satisfied by editing
    /// config — it is satisfied only by artwork that actually compiled.
    /// THE KEY LIVES IN TWO PLACES AND THIS LEG FOUND THAT OUT THE HARD WAY.
    ///
    /// Written first as `object(forInfoDictionaryKey: "CFBundleIconName")`,
    /// this went RED on a build whose icon had compiled correctly — `actool`
    /// ran, `Assets.car` shipped, `AppIcon60x60@2x.png` sat in the product.
    /// The top-level key was genuinely absent; the name was written NESTED at
    /// `CFBundleIcons.CFBundlePrimaryIcon.CFBundleIconName`. A leg reading
    /// only the top level would have reported "no icon" about an app that has
    /// one — the exact wrong-subject failure this file's control exists for,
    /// arriving one level down from where the control looks.
    ///
    /// So the leg asks the question it means: is an icon NAMED anywhere the
    /// OS reads. Both locations are accepted and the failure message prints
    /// both, because which one a given toolchain and destination writes is
    /// not something this suite should pin.
    func testTheBuiltPlistNamesAnIcon() throws {
        let app = try hostAppBundle()
        let topLevel = app.object(forInfoDictionaryKey: "CFBundleIconName") as? String
        let primary = (app.object(forInfoDictionaryKey: "CFBundleIcons") as? [String: Any])
            .flatMap { $0["CFBundlePrimaryIcon"] as? [String: Any] }
            .flatMap { $0["CFBundleIconName"] as? String }

        XCTAssertTrue(
            topLevel == "AppIcon" || primary == "AppIcon",
            "no icon named in the built Info.plist — top-level "
                + "CFBundleIconName=\(topLevel ?? "absent"), nested "
                + "CFBundlePrimaryIcon.CFBundleIconName=\(primary ?? "absent"). "
                + "The asset catalog compiler emitted no icon; App Store "
                + "validation rejects this and nothing else here reports it."
        )
    }

    /// The catalog compiled a RASTERISED icon, not just the key.
    ///
    /// SECOND CHANNEL FOR THE ICON SPECIFICALLY. The plist key and the
    /// `Assets.car` legs can BOTH be satisfied by a catalog that carries only
    /// the colour set plus a stale key — so neither of them alone separates
    /// "an icon set exists" from "an icon IMAGE compiled". `actool` writes
    /// rasterised PNGs beside the product for the primary icon; their
    /// presence is bytes derived from the artwork, which config cannot fake.
    ///
    /// 🔴 THE ARTWORK THIS LEG IS GREEN AGAINST IS A PLACEHOLDER.
    /// `AppIcon-1024-PLACEHOLDER.png` is a generated mark — a dark field and a
    /// red glyph, five sampled colours — not brand artwork, and it is a
    /// TRACKED file, so it ships if nobody replaces it. This leg asserts
    /// PACKAGING and is blind to that: it is exactly as green on the
    /// placeholder as it will be on the real icon, by design, because its
    /// subject is whether `actool` produced an image at all.
    ///
    /// The replacement is merakizzz's lane (1024² source, no alpha). The gate
    /// is NOT here — a leg pinning the placeholder's sha would go red on the
    /// good event, which trains the reader to delete it. It is a hard item on
    /// the upload checklist instead: `docs/STORE-UPLOAD-CHECKLIST.md`, item
    /// "icon sha ≠ placeholder sha", blocking submission, not the suite.
    func testTheCatalogRasterisedAnIcon() throws {
        let app = try hostAppBundle()
        let names = (try? FileManager.default.contentsOfDirectory(atPath: app.bundleURL.path)) ?? []
        let icons = names.filter { $0.hasPrefix("AppIcon") && $0.hasSuffix(".png") }
        XCTAssertFalse(
            icons.isEmpty,
            "no rasterised AppIcon*.png in the product — the icon set is "
                + "named but no artwork compiled from it"
        )
    }

    /// The compiled catalog exists beside the plist.
    ///
    /// SECOND CHANNEL, DELIBERATELY. `CFBundleIconName` is a STRING the
    /// toolchain wrote; `Assets.car` is the BYTES it wrote. They can disagree
    /// — a catalog that compiles only a colour set produces an `Assets.car`
    /// and no icon key, which is precisely the intermediate state this commit
    /// passes through. Asserting both separates "catalog present" from "icon
    /// present", and a single leg could not.
    func testTheCompiledAssetCatalogShipsInTheBundle() throws {
        let app = try hostAppBundle()
        let car = app.bundleURL.appendingPathComponent("Assets.car")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: car.path),
            "Assets.car absent from \(app.bundleURL.lastPathComponent) — no "
                + "asset catalog was compiled into the product"
        )
    }

    /// The BUILT product claims iPhone only.
    ///
    /// THE REPORTER FOR A LINE THAT LIVES IN A TRACKED FILE BUT ACTS THROUGH
    /// AN UNTRACKED ONE. `TARGETED_DEVICE_FAMILY: "1"` is stated in
    /// `project.yml`, but what reaches the product is whatever the pbxproj
    /// carries — and `.gitignore` excludes the pbxproj, so a stale or
    /// regenerated project can put "1,2" back with the tracked config still
    /// reading "1" in the diff. Neither a grep of `project.yml` nor a review
    /// of the commit can tell those apart; only the built plist can.
    ///
    /// `UIDeviceFamily` is the plist form of that setting: `[1]` iPhone,
    /// `[1, 2]` iPhone and iPad. Claiming iPad makes an iPad screenshot set
    /// MANDATORY at submission for a canvas nothing here has laid out, so the
    /// wrong value costs a rejected upload rather than a crash.
    func testTheBuiltProductClaimsIPhoneOnly() throws {
        let app = try hostAppBundle()
        let families = app.object(forInfoDictionaryKey: "UIDeviceFamily") as? [Int]
        XCTAssertEqual(
            families,
            [1],
            "UIDeviceFamily=\(families.map(String.init(describing:)) ?? "absent") "
                + "in the built product; project.yml says \"1\". The pbxproj is "
                + "untracked, so this disagreement is invisible in a diff."
        )
    }

    /// The launch screen names the colour resource rather than defaulting.
    ///
    /// `UILaunchScreen: {}` is VALID and renders the system default background
    /// — white in light mode — in front of a 0x0D0806 app. So the defect this
    /// guards is not a malformed key, it is a WELL-FORMED EMPTY ONE, which no
    /// validator anywhere objects to. The assertion is that the dictionary
    /// names our resource; an empty dictionary fails it.
    func testTheLaunchScreenNamesTheDarkBackground() throws {
        let app = try hostAppBundle()
        let launch = app.object(forInfoDictionaryKey: "UILaunchScreen") as? [String: Any]
        XCTAssertEqual(
            launch?["UIColorName"] as? String,
            "LaunchBackground",
            "UILaunchScreen does not name a colour resource — cold start "
                + "renders the system default (white) before the app draws"
        )
    }

    /// Portrait is DECLARED, not inherited from the OS default.
    ///
    /// Absent `UISupportedInterfaceOrientations` the system supplies portrait
    /// plus both landscapes on iPhone, so the app rotates into two geometries
    /// nobody laid out. Nothing in Swift can observe that: `orientation` is 0
    /// hits across Sources and Tests, which is precisely why the OS default
    /// was invisible for the whole life of this branch.
    ///
    /// The assertion is EXACT SET EQUALITY, not `contains`. `contains
    /// portrait` is satisfied by the OS default too — it would be green on the
    /// tree this leg was written to change, which makes it no instrument at
    /// all. Equality is the only form that separates "we chose portrait" from
    /// "we chose nothing and portrait happens to be in the list".
    func testTheAppDeclaresPortraitOnly() throws {
        let app = try hostAppBundle()
        let declared = app.object(
            forInfoDictionaryKey: "UISupportedInterfaceOrientations"
        ) as? [String]
        XCTAssertEqual(
            declared,
            ["UIInterfaceOrientationPortrait"],
            "orientations are not exactly [portrait] — the app either "
                + "inherits the OS default (portrait + both landscapes) or "
                + "claims a geometry no view was laid out against"
        )
    }

    /// Export compliance is answered in the plist, so uploads are not
    /// interactive.
    ///
    /// APERTURE, AND IT IS THE POINT OF THIS LEG: this asserts the key is
    /// PRESENT and `false`. It cannot and does not verify that `false` is the
    /// legally correct answer — that is a statement about a shipped binary
    /// under export regulation, and no test in any suite can make it. The
    /// supporting census (`CryptoKit`, `CommonCrypto`, `SecKey`, `CC_SHA` = 0
    /// files) lives in project.yml beside the key; confirmation is merakizzz's
    /// and it gates upload.
    ///
    /// What this leg genuinely guards is the ABSENCE case: without the key,
    /// App Store Connect blocks every upload on a prompt, and nothing in the
    /// build reports that until someone is mid-submission.
    func testExportComplianceIsDeclared() throws {
        let app = try hostAppBundle()
        let declared = app.object(
            forInfoDictionaryKey: "ITSAppUsesNonExemptEncryption"
        ) as? Bool
        XCTAssertEqual(
            declared,
            false,
            "ITSAppUsesNonExemptEncryption is absent or true — every upload "
                + "stalls on an interactive export-compliance prompt"
        )
    }

    /// The device-capability floor is stated rather than inferred.
    ///
    /// Redundant with the iOS 17 deployment target TODAY — every device that
    /// can run iOS 17 is arm64 — and that redundancy is the reason to assert
    /// it: the requirement stops being a consequence of a number in a
    /// different file. The leg is exact-set for the same reason as the
    /// orientation one, and it is the reporter if anyone ever adds a
    /// capability here, because each entry silently REMOVES devices from the
    /// store listing with no other signal.
    func testTheDeviceCapabilityFloorIsExactlyArm64() throws {
        let app = try hostAppBundle()
        let caps = app.object(
            forInfoDictionaryKey: "UIRequiredDeviceCapabilities"
        ) as? [String]
        XCTAssertEqual(
            caps,
            ["arm64"],
            "required capabilities are not exactly [arm64] — an added entry "
                + "narrows the install base with no other reporter"
        )
    }
}
