// GENERATED — DO NOT EDIT. Regenerate with scripts/build-xcframework.sh
//
//   $ ./scripts/build-xcframework.sh
//     -> cargo run --bin uniffi-bindgen -- generate \
//          --library rust/zeus-core-bridge/target/aarch64-apple-ios/release/libzeus_core_bridge.a \
//          --language swift --out-dir Sources/ZeusCoreFFI/
//
// Checked in deliberately: it is compiled as app source, so the app builds on
// any Mac with Xcode and no Rust toolchain. Only LINKING needs the archive,
// which is gitignored and rebuilt by the same script.
//
// crate tree 0000000000000000000000000000000000000000 · dep pin fe40ddb8 · rustc 1.95.0 (59807616e 2026-04-14)
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(zeus_core_bridgeFFI)
import zeus_core_bridgeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zeus_core_bridge_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zeus_core_bridge_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The bridge IS the runtime owner. `init` constructs it; it lives for the
 * process. Every async core call is driven by this runtime — there is no
 * ambient executor on the phone.
 */
public protocol ZeusCoreProtocol : AnyObject {
    
    /**
     * Number of files indexed at `init`.
     *
     * Exported for one reason: it is the only way a caller can tell "the query
     * matched nothing" from "the index is empty", which are the two states the
     * pin's unpopulated `FileIndex` makes indistinguishable. A vacuity probe,
     * not a statistic.
     */
    func indexSize()  -> UInt32
    
    /**
     * Append a fact to workspace memory.
     */
    func remember(fact: String) throws 
    
    /**
     * Search the workspace file index.
     *
     * **Contract, stated because it is narrower than the name:** this reads an
     * index of the workspace files scanned at `init`. It is a SNAPSHOT, not a
     * live view — a file written after `init` is invisible until the process
     * restarts. Re-scan policy is deferred to v1.1; when Mnemosyne is measured
     * green under the iOS SDK it becomes a swap behind this same export and
     * nothing in Swift changes.
     */
    func search(query: String)  -> [SearchHit]
    
    /**
     * Send `text` on `session_id`, streaming tokens into `sink`.
     *
     * Blocks the calling thread for the duration — Swift calls it off the main
     * actor. Chosen over a fire-and-forget spawn because a detached task whose
     * handle nobody holds cannot be cancelled and cannot report a panic; the
     * caller owning the thread is the honest shape for v1.
     */
    func send(sessionId: String, text: String, sink: TokenSink) throws 
    
    /**
     * List known sessions, newest first.
     */
    func sessions() throws  -> [SessionInfo]
    
    /**
     * Select the model route. `id` is a provider prefix (`anthropic`,
     * `openai`, `ollama`, `gemini`, `groq`, …).
     *
     * The prefix→enum map is `Provider::from_prefix` (zeus-core:8922) and NOT a
     * second table here: it is the single source of truth for `{provider}/{model}`
     * resolution, carries the aliases, and returns `None` on unrecognized input
     * so the caller must decide the fallback (#559 — no silent mis-route to
     * Anthropic's env key). A local table would be a second truth that drifts.
     */
    func setProvider(id: String, model: String, key: String) throws 
    
}

/**
 * The bridge IS the runtime owner. `init` constructs it; it lives for the
 * process. Every async core call is driven by this runtime — there is no
 * ambient executor on the phone.
 */
open class ZeusCore:
    ZeusCoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zeus_core_bridge_fn_clone_zeuscore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zeus_core_bridge_fn_free_zeuscore(pointer, $0) }
    }

    
    /**
     * Build the core rooted at `workspace_dir`.
     *
     * Constructor, not a free function: the runtime must outlive every call,
     * and a `#[uniffi::constructor]` is the only shape where Swift's ARC keeps
     * it alive for us.
     */
public static func `init`(workspaceDir: String)throws  -> ZeusCore {
    return try  FfiConverterTypeZeusCore.lift(try rustCallWithError(FfiConverterTypeBridgeError.lift) {
    uniffi_zeus_core_bridge_fn_constructor_zeuscore_init(
        FfiConverterString.lower(workspaceDir),$0
    )
})
}
    

    
    /**
     * Number of files indexed at `init`.
     *
     * Exported for one reason: it is the only way a caller can tell "the query
     * matched nothing" from "the index is empty", which are the two states the
     * pin's unpopulated `FileIndex` makes indistinguishable. A vacuity probe,
     * not a statistic.
     */
open func indexSize() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_zeus_core_bridge_fn_method_zeuscore_index_size(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Append a fact to workspace memory.
     */
open func remember(fact: String)throws  {try rustCallWithError(FfiConverterTypeBridgeError.lift) {
    uniffi_zeus_core_bridge_fn_method_zeuscore_remember(self.uniffiClonePointer(),
        FfiConverterString.lower(fact),$0
    )
}
}
    
    /**
     * Search the workspace file index.
     *
     * **Contract, stated because it is narrower than the name:** this reads an
     * index of the workspace files scanned at `init`. It is a SNAPSHOT, not a
     * live view — a file written after `init` is invisible until the process
     * restarts. Re-scan policy is deferred to v1.1; when Mnemosyne is measured
     * green under the iOS SDK it becomes a swap behind this same export and
     * nothing in Swift changes.
     */
open func search(query: String) -> [SearchHit] {
    return try!  FfiConverterSequenceTypeSearchHit.lift(try! rustCall() {
    uniffi_zeus_core_bridge_fn_method_zeuscore_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Send `text` on `session_id`, streaming tokens into `sink`.
     *
     * Blocks the calling thread for the duration — Swift calls it off the main
     * actor. Chosen over a fire-and-forget spawn because a detached task whose
     * handle nobody holds cannot be cancelled and cannot report a panic; the
     * caller owning the thread is the honest shape for v1.
     */
open func send(sessionId: String, text: String, sink: TokenSink)throws  {try rustCallWithError(FfiConverterTypeBridgeError.lift) {
    uniffi_zeus_core_bridge_fn_method_zeuscore_send(self.uniffiClonePointer(),
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(text),
        FfiConverterCallbackInterfaceTokenSink.lower(sink),$0
    )
}
}
    
    /**
     * List known sessions, newest first.
     */
open func sessions()throws  -> [SessionInfo] {
    return try  FfiConverterSequenceTypeSessionInfo.lift(try rustCallWithError(FfiConverterTypeBridgeError.lift) {
    uniffi_zeus_core_bridge_fn_method_zeuscore_sessions(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Select the model route. `id` is a provider prefix (`anthropic`,
     * `openai`, `ollama`, `gemini`, `groq`, …).
     *
     * The prefix→enum map is `Provider::from_prefix` (zeus-core:8922) and NOT a
     * second table here: it is the single source of truth for `{provider}/{model}`
     * resolution, carries the aliases, and returns `None` on unrecognized input
     * so the caller must decide the fallback (#559 — no silent mis-route to
     * Anthropic's env key). A local table would be a second truth that drifts.
     */
open func setProvider(id: String, model: String, key: String)throws  {try rustCallWithError(FfiConverterTypeBridgeError.lift) {
    uniffi_zeus_core_bridge_fn_method_zeuscore_set_provider(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(model),
        FfiConverterString.lower(key),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZeusCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ZeusCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ZeusCore {
        return ZeusCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ZeusCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZeusCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ZeusCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZeusCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> ZeusCore {
    return try FfiConverterTypeZeusCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZeusCore_lower(_ value: ZeusCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeZeusCore.lower(value)
}


/**
 * One hit from the workspace file index.
 */
public struct SearchHit {
    public var path: String
    public var name: String
    public var score: Double
    public var context: String?
    public var lineNumber: UInt32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, name: String, score: Double, context: String?, lineNumber: UInt32?) {
        self.path = path
        self.name = name
        self.score = score
        self.context = context
        self.lineNumber = lineNumber
    }
}



extension SearchHit: Equatable, Hashable {
    public static func ==(lhs: SearchHit, rhs: SearchHit) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        if lhs.context != rhs.context {
            return false
        }
        if lhs.lineNumber != rhs.lineNumber {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(name)
        hasher.combine(score)
        hasher.combine(context)
        hasher.combine(lineNumber)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchHit {
        return
            try SearchHit(
                path: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf), 
                context: FfiConverterOptionString.read(from: &buf), 
                lineNumber: FfiConverterOptionUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SearchHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
        FfiConverterOptionString.write(value.context, into: &buf)
        FfiConverterOptionUInt32.write(value.lineNumber, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lift(_ buf: RustBuffer) throws -> SearchHit {
    return try FfiConverterTypeSearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lower(_ value: SearchHit) -> RustBuffer {
    return FfiConverterTypeSearchHit.lower(value)
}


/**
 * A session, flattened for Swift. `Session::list` yields
 * `(String, DateTime<Utc>)`; `DateTime` has no UniFFI representation, so the
 * timestamp crosses as RFC3339 text and Swift parses it. Deliberate: an i64
 * epoch would silently lose the timezone the core carries.
 */
public struct SessionInfo {
    public var id: String
    public var updatedAtRfc3339: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, updatedAtRfc3339: String) {
        self.id = id
        self.updatedAtRfc3339 = updatedAtRfc3339
    }
}



extension SessionInfo: Equatable, Hashable {
    public static func ==(lhs: SessionInfo, rhs: SessionInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.updatedAtRfc3339 != rhs.updatedAtRfc3339 {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(updatedAtRfc3339)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionInfo {
        return
            try SessionInfo(
                id: FfiConverterString.read(from: &buf), 
                updatedAtRfc3339: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SessionInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.updatedAtRfc3339, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionInfo_lift(_ buf: RustBuffer) throws -> SessionInfo {
    return try FfiConverterTypeSessionInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionInfo_lower(_ value: SessionInfo) -> RustBuffer {
    return FfiConverterTypeSessionInfo.lower(value)
}


public enum BridgeError {

    
    
    case NoProvider
    case Core(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBridgeError: FfiConverterRustBuffer {
    typealias SwiftType = BridgeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NoProvider
        case 2: return .Core(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NoProvider:
            writeInt(&buf, Int32(1))
        
        
        case let .Core(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension BridgeError: Equatable, Hashable {}

extension BridgeError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




/**
 * Swift implements this; the bridge calls it from the runtime thread as tokens
 * arrive. `on_token` may be called many times, then exactly one of
 * `on_complete` / `on_error`.
 */
public protocol TokenSink : AnyObject {
    
    func onToken(token: String) 
    
    func onComplete(fullText: String) 
    
    func onError(message: String) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceTokenSink {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceTokenSink = UniffiVTableCallbackInterfaceTokenSink(
        onToken: { (
            uniffiHandle: UInt64,
            token: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTokenSink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onToken(
                     token: try FfiConverterString.lift(token)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onComplete: { (
            uniffiHandle: UInt64,
            fullText: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTokenSink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onComplete(
                     fullText: try FfiConverterString.lift(fullText)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTokenSink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceTokenSink.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface TokenSink: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitTokenSink() {
    uniffi_zeus_core_bridge_fn_init_callback_vtable_tokensink(&UniffiCallbackInterfaceTokenSink.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceTokenSink {
    fileprivate static var handleMap = UniffiHandleMap<TokenSink>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceTokenSink : FfiConverter {
    typealias SwiftType = TokenSink
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [SearchHit]

    public static func write(_ value: [SearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSessionInfo: FfiConverterRustBuffer {
    typealias SwiftType = [SessionInfo]

    public static func write(_ value: [SessionInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSessionInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SessionInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [SessionInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSessionInfo.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zeus_core_bridge_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_zeuscore_index_size() != 24630) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_zeuscore_remember() != 52311) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_zeuscore_search() != 45840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_zeuscore_send() != 53202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_zeuscore_sessions() != 18996) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_zeuscore_set_provider() != 9512) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_constructor_zeuscore_init() != 65523) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_tokensink_on_token() != 11436) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_tokensink_on_complete() != 2393) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeus_core_bridge_checksum_method_tokensink_on_error() != 38699) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitTokenSink()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all